### ISSUE TITLE
List of creepypastas

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#1]
## Value proposition

**As a** user
**I need** to have a list of creepypastas
**to be able to** read them

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/157017632-1bc725a1-9a90-4bf4-989a-98554ad1d009.png"/>

## Acceptance Criteria

- [x] Card component is shown
- [x] Word count is shown under text
- [x] Heading is shown on page

## Tasks

- [x] Global styles
- [x] components/Card
    - [x] Storybook
    - [x] Tests
    - [x] Styling
- [x] Adding Header and styling it (not fixed)
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
- [x] Add to app
