### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#10]
## Value proposition

**As a** user
**I need** have my own profile
**to be able to** share my interests with other users

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/158190013-bbbe51c5-6e83-4adc-add9-b59bc41f01fa.png" />

## Acceptance Criteria

- [x] Profile page
- [x] Navigation between profile, bookmark and all

## Tasks

- [x] pages/ProfilePage
- [x] Add static information about user
- [x] Route to ProfilePage
- [x] Navigate to Profile Page
- [x] Add styling
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
