### ISSUE TITLE
Save Bookmarks to Profile Page

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#11]
## Value proposition

**As a** user
**I need** safe my bookmarks to my profile page
**to be able to** to show other users what creepypastas I like

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/158190229-806a2b50-de12-4599-8e96-38ec51714fd9.png" />

## Acceptance Criteria

- [x] Bookmarked creepypastas are shown on profile page
- [x] Only navigate between profile page and all page
- [x] Project ReadMe

## Tasks

- [x] Add bookmarkPage logic to profilePage
- [x] Remove route to bookmarkpage
- [x] Remove navigation to bookmarkpage
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
- [x] Add ReadMe
