### ISSUE TITLE
Create creepypastas

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#12]
## Value proposition

**As a** user
**I need** create my own creepypastas
**to be able to** to share them with others

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/158190409-570f5776-5d73-4eda-b092-df913a13958d.png"/>

## Acceptance Criteria

- [x] Create Page
- [x] Navigation to Create Page
- [x] Form with two inputs and one textarea to write creepypasta
- [x] After saving the story is shown on page all

## Tasks

- [x] pages/CreatePage
- [x] components/formCreepypasta
    - [x] Title input, required
    - [x] Text textarea, required
    - [x] Image input, required
    - [x] Wordcounter
    - [x] Test
    - [x] Storybook
- [x] Route to CreatePage
- [x] Navigation to CreatePage
- [x] Add styling
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
