### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#17]
## Value proposition

**As a** User
**I need** a navigation bar
**to be able to** navigate more comfortable

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/158573122-684e83e2-a930-49e4-b3fc-30566637570b.png" />

## Acceptance Criteria

- [x] Navigation is fixed
- [x] Each icon leads to different page

## Tasks

- [x] components/NavBar
    - [x] styling
    - [x] tests
- [x] Implement NavBar in each page
- [x] Delete previous navigation
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
