### ISSUE TITLE
Safe written stories in profile page

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#18]
## Value proposition

**As a** User
**I need** to see my written stories on my profile page
**to be able to** find them easier

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/158573765-31f5d3c7-26aa-4eed-adfb-2b83d8e194cf.png" />

## Acceptance Criteria

- [x] Profile Page has two parts, spookmarked and my stories
- [x] Written stories are shown on page all and on profile page

## Tasks

- [x] Form saves onSubmit to page all and profile
- [x] Implement sub-routes in profile page to either spookmarked or my stories
- [x] Adapt styling in profile page
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
