### ISSUE TITLE
Delete or edit creepypasta

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#19]
## Value proposition

**As a** User
**I need** delete or edit my creepypastas
**to be able to**

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/158576370-95e333af-c446-4d6c-bfe3-9de3aa826184.png" />

## Acceptance Criteria

- [x] Written stories have two extra clickable icons
- [x] Pen icon leads to the creepypasta edit
- [x] Trash icon can delete creepypasta
- [x] Pop up is shown, when your click on delete, to confirm
- [x] Deleted creepypastas are not shown on all page and profile page

## Tasks

- [x] page/EditPage
- [x] Add Router in pen icon to EditPage
- [x] component/DeleteCreepypasta
    - [x] styling
    - [x] tests
- [x] Add pop up to confirm delete 
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
