### ISSUE TITLE
Click on card to show text

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#2]
## Value proposition

**As a** user
**I need** click on a card
**to be able to** read the story easier

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/157480134-65f482d0-ba0c-43a3-bcca-098793de6ef8.png">

## Acceptance Criteria

- [x] By clicking on a Button on the card, your are redirected to a new Page
- [x] Click arrow button (top or bottom) to go back to main page
- [x] On the card is a picture shown, instead of text

## Tasks

- [x] Implement react router
- [x] Button on Cards redirects to read page
- [x] Add NanoId for unique key
- [x] components/Card
    - [x] Add Test
    - [x] Storybook
    - [x] Add styling
- [x] Arrow Button top left and bottom right to go back 
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
