### ISSUE TITLE
Feel good Page

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#23]
## Value proposition

**As a** User
**I need** a feel good page
**to be able to** calm down, after being scared

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/158989538-328af096-c54f-4221-9e6f-d79c479af6a5.png" />

## Acceptance Criteria

- [x] Route to new page
- [x] New page

## Tasks

- [x] page/FeelGood
    - [x] styling 
- [x] React router to page
- [x] Import icon
- [x] Style and place icon on profile page
- [x] Clicking on icon leads to feel good page
- [x] Clicking on arrow leads back from page
- [x] Read me update
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
