### ISSUE TITLE
Feel good page with API

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#24]
## Value proposition

**As a** User
**I need** to see cute cats
**to be able to** calm down even better

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/158990296-e33db198-1b6f-4973-95ed-4db0257e5cc3.png" />

## Acceptance Criteria

- [x] API for cat images
- [x] Image changes when clicked

## Tasks

- [x] Research API
- [x] Implement API
- [x] Add styling to fetched pictures
- [x] Update styling on feel good page
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
