### ISSUE TITLE
Edit your name

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#28]
## Value proposition

**As a** User
**I need** be able to edit my name
**to be able to** let other users know what my actual name is

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/159509456-43751172-d41c-4c3c-9657-e6404856d427.png" />

## Acceptance Criteria

- [x] By clicking the name you can edit it

## Tasks

- [x] Add function
- [x] Add icon
- [x] Adapt styling on profile page
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
