### ISSUE TITLE
Upload your profile picture

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#29]
## Value proposition

**As a** User
**I need** to upload my own profile picture
**to be able to** to show other users how I look

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/159510251-acdea0fe-0d1f-4a26-b29c-d69cf14af6e5.png" />

## Acceptance Criteria

- [x] By clicking on the upload icon, you can upload a picture
- [x] By clicking on the about me text, you can add your own information

## Tasks

- [x] Add image upload function
- [x] Add text edit function
- [x] Add icons
- [x] Adapt styling on profile page
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
