### ISSUE TITLE
Bookmark a card

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#3]
## Value proposition

**As a** user
**I need** to bookmark cards
**to be able to** find them faster

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/157644235-99068ecd-e3ad-40c4-8fe0-ba80cc5052f3.png"/>

## Acceptance Criteria

- [x] Toggle bookmark button that changes color when active
- [x] Page bookmarks
- [x] Navigation between pages
- [x] Bookmarked card is shown on page bookmarks
- [x] If nothing is bookmarked, empty state is shown

## Tasks

- [x] Download fonts and implement them
- [x] Spookmark toggle Button
- [x] React router for Spookmarks  on top right corner
- [x] pages/Spookmark
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
