### ISSUE TITLE
Upload Images to Creepypasta

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#32]
## Value proposition

**As a** User
**I need** a picture upload when I write my creepypastas
**to be able to** add a picture more comfortable

## Description

<img height="400" src="https://user-images.githubusercontent.com/94109611/160096105-04d1a36c-2e24-43dc-9fab-4fa77593e33d.png" />

## Acceptance Criteria

- [ ] Uploading a picture
- [ ] If creepypasta is edited, old picture is shown and can be replaced with a new one

## Tasks

- [ ] Add function to Form.js
- [ ] Adapt styling
- [ ] Check accessibility
- [ ] Test on mobile (vertically and horizontally)
