### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#33]
## Value proposition

**As a** Programmer
**I need** to refactor my code
**to be able to** make it easier for others to understand

## Description

Code is cleaner

## Acceptance Criteria

- [x] Code is cleaner
- [x] Code is easier to read

## Tasks

- [x] Clean up code
- [x] Delete unnecessary code
- [x] Delete unnecessary styling
- [x] Add tests
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
