### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#37]
## Value proposition

**As a** User
**I need** a informative ReadMe
**to be able to** get to know the app and know how to install it

## Description

Update and modify ReadMe.

## Acceptance Criteria

- [x] Informative ReadMe

## Tasks

- [x] Update tech stack
- [x] Check for spelling errors
- [x] Add screenshots of app
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
