### ISSUE TITLE
Implement searchbar

### ISSUE THREAD

**Issue by celinevo** [celinevo/capstone-project#4]
## Value proposition

**As a** user
**I need** to search a title
**to be able to** find it faster

## Description
<img height="400" src="https://user-images.githubusercontent.com/94109611/158189811-5f992635-fb3a-4cde-9639-ed62918d07d7.png"/>

## Acceptance Criteria

- [x] Searchbar is shown on main page
- [x] By searching a title, the card with the same title is shown
- [x] Search is not case sensitive
- [x] If searched title is not found, error massage is shown
- [x] More creepypastas to read

## Tasks

- [x] component/Searchbar
    - [x] Storybook
    - [x] Tests
    - [x] Styling 
- [x] Add error massage
- [x] Add more creepypastas for the user to read
- [x] Check accessibility
- [x] Test on mobile (vertically and horizontally)
